version: "3.9"

services:
  ml:
    build:
      context: ./ml-api
      dockerfile: Dockerfile
    container_name: studentmanagement-ml-api
    ports:
      - "8000:8000"
    restart: unless-stopped
