upstream face_embedding_upstream {
    least_conn;
    server face-embedding:8000;
}

server {
    listen 80;

    location /health {
        proxy_pass http://face_embedding_upstream/health;
        proxy_set_header Host $host;
    }

    # Reverse-proxy route policy:
    # /embedding requests are routed to face embedding replicas.
    location /embedding {
        proxy_pass http://face_embedding_upstream/embedding;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
