CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL,
    action VARCHAR(128) NOT NULL,
    endpoint VARCHAR(255) NOT NULL,
    http_method VARCHAR(16) NOT NULL,
    status_code INTEGER NOT NULL,
    tenant_id BIGINT,
    ip_address VARCHAR(64),
    user_agent VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_actor_time ON audit_log (username, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_tenant_time ON audit_log (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_endpoint ON audit_log (endpoint);
